### PR TITLE
Remove keywords 'or' in Platform Expression

### PR DESCRIPTION
**Pull request by LilyWangLL**
Keywords `or` is invalid, this change from https://github.com/microsoft/vcpkg-tool/pull/267, remove it from **vcpkg-json.md**.

https://github.com/microsoft/vcpkg-tool/blob/2e31d678b42aa56c3a44083d431829158814ded6/src/vcpkg-test/platform-expression.cpp#LL506C28-L506C28
```
invalid logic expression, use '|' instead of 'or'
```

Fixes https://github.com/microsoft/vcpkg/issues/31683

### CODE REVIEW

**Comment by dg0yt** [comment]
I would assume that the documentation for `not` and `and` needs to be fixed, too.

**Comment by LilyWangLL** [comment]
> I would assume that the documentation for `not` and `and` needs to be fixed, too.

I tested `not` and `and` and they work fine.

**Comment by dg0yt** [comment]
Then consistency would imply that `or` works, too. Principle of least surprise.

**Comment by autoantwort** [comment]
Never understand why https://github.com/microsoft/vcpkg-tool/pull/267 was merged. Afaik it is used by no one and added a second syntax for the same thing.

**Comment by LilyWangLL** [comment]
cc @@markle11m cc @vicroms

**Comment by vicroms** [comment]
@autoantwort  this was part of the `ce` (artifacts) merger, we had to support their platform expressions which were implemented using media queries. 

@LilyWangLL we should add a text explaining that while not accepted `or` is a reserved keyword.

**Comment by vicroms** [comment]
@LilyWangLL could you [apply this patch](
https://github.com/microsoft/vcpkg-docs/commit/b550af0ecc9a0cfdc210aeab2d1bab32aaaa84a0.patch) to fix some lint issues in this article.

**Comment by LilyWangLL** [comment]
> @LilyWangLL could you [apply this patch](https://github.com/microsoft/vcpkg-docs/commit/b550af0ecc9a0cfdc210aeab2d1bab32aaaa84a0.patch) to fix some lint issues in this article.

Done, thanks for your help.

**Review by vicroms — APPROVED** [review]

**Pull request merged**
